cp ./out/drivers/staging/qcacld-3.0/wlan.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/soc/swr_ctrl_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/soc/swr_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/soc/pinctrl_wcd_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/dsp/adsp_loader_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/dsp/q6_pdr_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/dsp/usf_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/dsp/codecs/native_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/dsp/q6_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/dsp/q6_notifier_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/platform_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/stub_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/cs35l41/cs35l41_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/wsa881x_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/wcd_core_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/mbhc_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/tas2557/tas2557_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/wcd9360/wcd9360_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/wcd_cpe_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/hdmi_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/wcd934x/wcd934x_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/wcd_spi_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/codecs/wcd9xxx_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/asoc/machine_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/ipc/wglink_dlkm.ko /media/sf_VMxfer/LOSdrivers/
cp ./out/techpack/audio/ipc/apr_dlkm.ko /media/sf_VMxfer/LOSdrivers/
